# Lab 1 – Basic NumPy Operations

**Course:** Artificial Intelligence Algorithms and Mathematics (CSCN8000)  
**Student Name:** Krishna Reddy Bovilla  
**Student ID:** 9050861  

- **GitHub Repository:** [https://github.com/Conestoga-College-Poworoznyk/assignment1-kittuai](https://github.com/Conestoga-College-Poworoznyk/assignment1-kittuai)  
- **Live Notebook Page:** [https://kittuai.github.io/ai/](https://kittuai.github.io/ai/)


### importing numpy library for numy operations


In [2]:
import numpy as np

### 2.  Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [3]:
#  array from 1 to 20 and step with step 3
my_array = np.arange(1, 21, 3)
print("array with step 3:",my_array)

array with step 3: [ 1  4  7 10 13 16 19]


### 3.Create a new array of shape 3 with random numbers between 0 and 1.


In [4]:
# random numbers between 0 and 1
random_array = np.random.rand(3)
print("random numbers:",random_array)

random numbers: [0.7228626  0.93908393 0.01921186]


### 4.Create a 2 D array and perform the following operations: 


In [5]:
my_2darray = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print("2D array:")
print(my_2darray)


2D array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]


In [6]:
# to get first 2 rows
a = my_2darray[:2]
print("first two rows:")
print(a)

first two rows:
[[10 20 45]
 [30 12 16]]


In [7]:
# to get last 2 rows
b = my_2darray[1:]
print("last two rows:")
print(b)

last two rows:
[[30 12 16]
 [42 17 56]]


### Step 5: Stacking and Splitting 2x2 Arrays


In [8]:
# create arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("arr1:\n", arr1, "\n")
print("arr2:\n", arr2, "\n")

# vertical stack
vertical_stack = np.vstack((arr1, arr2))
print("vertical_stack:\n", vertical_stack, "\n")

# horizontal stack
horizantal_stack = np.hstack((arr1, arr2))
print("horizantal_stack:\n", horizantal_stack, "\n")

# split arr1 into two parts
split1, split2 = np.hsplit(arr1, 2)
print("split 1:\n", split1, "\n")
print("split 2:\n", split2, "\n")


arr1:
 [[1 2]
 [3 4]] 

arr2:
 [[5 6]
 [7 8]] 

vertical_stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

horizantal_stack:
 [[1 2 5 6]
 [3 4 7 8]] 

split 1:
 [[1]
 [3]] 

split 2:
 [[2]
 [4]] 



### Step 6: Check If Two Matrices Can Be Multiplied

In [9]:
# create two matrices
array1 = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
array2 = np.array([[4, 2], [6, 2], [4, 2]])

print("array 1:\n", arr1, "\n")
print("array 2:\n", arr2, "\n")

# multiply if shapes match
if array1.shape[1] == array2.shape[0]:
    result = np.dot(array1, array2)
    print("multiplication result:\n", result)
else:
    print("can't multiply, shape mismatch")


array 1:
 [[1 2]
 [3 4]] 

array 2:
 [[5 6]
 [7 8]] 

multiplication result:
 [[70 28]
 [70 30]
 [60 26]]


### Step 6 : When Matrix Multiplication Doesn't Work


In [10]:
# create two matrices that can't be multiplied
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7]])

print("a:\n", a, "\n")
print("b:\n", b, "\n")

# check if we can multiply
if a.shape[1] == b.shape[0]:
    res = np.dot(a, b)
    print("result:\n", res)
else:
    print("can't multiply, sizes don't match")


a:
 [[1 2]
 [3 4]] 

b:
 [[5 6 7]] 

can't multiply, sizes don't match


### explanation

We tried two examples:

- In the first one, we multiplied matrix `array 1` (3x3) with matrix `array 2` (3x2).  
  This works because the middle sizes match (3 and 3).

- In the second one, we tried to multiply matrix `a` (2x2) with matrix `b` (1x3).  
  This does not work because the middle sizes don’t match (2 and 1).

Matrix multiplication only works when:
**columns of the first matrix = rows of the second matrix**


### Step 7:  Create Arrays & Check Shape & Dimensions of x

In [11]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("shape of x:", x.shape)
print("number of dimensions of x:", x.ndim)


shape of x: (3,)
number of dimensions of x: 1


### Reshape x to (3,1) and Check New Shape & Dimensions

In [12]:
x_new = x.reshape(3, 1)
print("x after reshape:", x_new.shape)
print("x dimensions after reshape:", x_new.ndim)


x after reshape: (3, 1)
x dimensions after reshape: 2


### Reshape y to (3,1) and Check New Shape/Dimensions

In [13]:
y_new = y.reshape(3, 1)
# check original shape and dimensions of y
print("original shape of y:", y.shape)
print("original dimensions of y:", y.ndim)

# reshape y to 3 rows, 1 column
y_new = y.reshape(3, 1)
print("y after reshape:", y_new.shape)
print("y dimensions after reshape:", y_new.ndim)



original shape of y: (3,)
original dimensions of y: 1
y after reshape: (3, 1)
y dimensions after reshape: 2


### Step 8: Broadcasting


In [14]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([1, 2, 3])

# subtract
sub = a - b
print("a - b:\n", sub, "\n")

# multiply
mul = a * b
print("a * b:\n", mul)


a - b:
 [[0 0 0]
 [3 3 3]
 [6 6 6]] 

a * b:
 [[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


Broadcasting means NumPy lets us do math between a big array and a small one.

We used this matrix and array:

Matrix a :
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

Array b :
    [1, 2, 3]

Now we do:

#### Subtraction: a - b

Row 1: [1, 2, 3] - [1, 2, 3] = [0, 0, 0]  
Row 2: [4, 5, 6] - [1, 2, 3] = [3, 3, 3]  
Row 3: [7, 8, 9] - [1, 2, 3] = [6, 6, 6]

#### Multiplication: a * b

Row 1: [1, 2, 3] * [1, 2, 3] = [1, 4, 9]  
Row 2: [4, 5, 6] * [1, 2, 3] = [4, 10, 18]  
Row 3: [7, 8, 9] * [1, 2, 3] = [7, 16, 27]

Even though `b` is smaller, NumPy repeats it to match every row in `a`.  
This is called **broadcasting**, NumPy do math between arrays that are not the same size by matching them automatically.



## Step 9: Overview

This is a summary of what we did in each step of the lab using NumPy:

- **Step 1:** We started by importing the NumPy library so we could use its functions for arrays and matrix operations.

- **Step 2:** We created an array that starts from 1 and ends at 20, going up by 3. This helped us learn how to use `np.arange()` to make number sequences.`

- **Step 3:** We made a new array with 3 random numbers between 0 and 1 using `np.random.rand()`. This was our first look at generating random values in NumPy.

- **Step 4:** We created a 2D array and learned how to slice it. We took the first two rows and then the last two rows to understand how slicing works in two dimensions.

- **Step 5:** We made two 2x2 arrays and stacked them vertically and horizontally using `vstack` and `hstack`. We also split one of them into smaller arrays using `hsplit()`.

- **Step 6:** We tried matrix multiplication using `np.dot()`. First, we used two matrices that worked together, and then we showed a case where the shapes didn’t match, so the multiplication could not happen.

- **Step 7:** We created two 1D arrays and checked their shape and number of dimensions. Then we reshaped both into column-style (3,1) matrices and saw how the dimensions changed from 1D to 2D.

- **Step 8:** We used broadcasting to subtract and multiply a 1D array from a 3x3 matrix. We learned how NumPy automatically lines up the smaller array with each row of the bigger one to perform the operation.

This lab helped us understand the basics of NumPy, including arrays, slicing, reshaping, matrix operations, and broadcasting.


# Part - B

In [15]:
import numpy as np  # using numpy for matrix calculations

# System 1
# Equations: 
# 2x1 + 3x2 - 4x3 = 6
# x1 - 4x2 = 8

A1 = np.array([
    [2, 3, -4],
    [1, -4, 0]
])

b1 = np.array([6, 8])

sol1, _, _, _ = np.linalg.lstsq(A1, b1, rcond=None)

rank_A1 = np.linalg.matrix_rank(A1)
rank_aug1 = np.linalg.matrix_rank(np.column_stack((A1, b1)))
vars1 = A1.shape[1]

print("System 1 solution:", sol1)
print("Rank of A1:", rank_A1)
print("Rank of [A1|b1]:", rank_aug1)

if rank_A1 == rank_aug1 == vars1:
    print("Unique solution")
elif rank_A1 == rank_aug1 < vars1:
    print("Infinite solutions")
else:
    print("No solution")

# System 2
# 3y1 - 4y2 + 5y3 = 10
# -y1 + 2y2 - 4y3 = 8

A2 = np.array([
    [3, -4, 5],
    [-1, 2, -4]
])

b2 = np.array([10, 8])

sol2, _, _, _ = np.linalg.lstsq(A2, b2, rcond=None)

rank_A2 = np.linalg.matrix_rank(A2)
rank_aug2 = np.linalg.matrix_rank(np.column_stack((A2, b2)))
vars2 = A2.shape[1]

print("\nSystem 2 solution:", sol2)
print("Rank of A2:", rank_A2)
print("Rank of [A2|b2]:", rank_aug2)

if rank_A2 == rank_aug2 == vars2:
    print("Unique solution")
elif rank_A2 == rank_aug2 < vars2:
    print("Infinite solutions")
else:
    print("No solution")


System 1 solution: [ 1.6692112 -1.5826972 -1.8524173]
Rank of A1: 2
Rank of [A1|b1]: 2
Infinite solutions

System 2 solution: [ 7.46067416 -4.62921348 -6.17977528]
Rank of A2: 2
Rank of [A2|b2]: 2
Infinite solutions


### Part B – Explanation

### System 1

Equations:
1. 2*x1 + 3*x2 - 4*x3 = 6  
2. x1 - 4*x2 = 8  

- There are 3 unknowns (x1, x2, x3), but we only have 2 equations.  
- That means we can't get one exact answer — there could be many.  
- So, we use a NumPy function called `lstsq()` to get a best guess.  
- We also check the "rank" of the matrices to know how many answers are possible.

### System 2

Equations:
1. 3*y1 - 4*y2 + 5*y3 = 10  
2. -y1 + 2*y2 - 4*y3 = 8  

- This is also a case where we have 3 unknowns but only 2 equations.  
- We use the same method as before to solve it.  
- After solving, we print the values we got for y1, y2, and y3.  
- Then we check the ranks again to see how many answers are possible.

### solutions explaination 
- If both matrix ranks are the same and equal to the number of unknowns → one solution  
- If both ranks are the same but less than the number of unknowns → many solutions  
- If the ranks are not equal → no solution
